import {
  MarketStatus,
  Quote,
  Candle,
  TechnicalsPayload,
  OptionChainSnapshot,
  NewsArticle,
  FiiDiiFlow,
  CalendarEvent,
  FullIndexSnapshot,
  AlertRule,
  WatchlistItem
} from '../types';

import {
  getMarketStatus as mockMarketStatus,
  generateQuote as mockQuote,
  generateCandles as mockCandles,
  generateTechnicals as mockTechnicals,
  generateOptionChain as mockOptionChain,
  getFullSnapshot as mockFullSnapshot,
  SAMPLE_NEWS,
  SAMPLE_FII_DII,
  SAMPLE_CALENDAR
} from './mockData';

const API_BASE = '/api';

export async function fetchMarketStatus(): Promise<MarketStatus> {
  try {
    const res = await fetch(`${API_BASE}/market/status`);
    if (!res.ok) throw new Error('API offline');
    const json = await res.json();
    return json.data;
  } catch {
    return mockMarketStatus();
  }
}

export async function fetchIndexSnapshot(symbol: string): Promise<FullIndexSnapshot> {
  try {
    const res = await fetch(`${API_BASE}/indices/${symbol}`);
    if (!res.ok) throw new Error('API offline');
    const json = await res.json();
    return json.data;
  } catch {
    return mockFullSnapshot(symbol);
  }
}

export async function fetchCandles(symbol: string, interval: '5m' | '15m' | '1h' | '1d' = '5m'): Promise<Candle[]> {
  try {
    const res = await fetch(`${API_BASE}/indices/${symbol}/ohlcv?interval=${interval}`);
    if (!res.ok) throw new Error('API offline');
    const json = await res.json();
    return json.data;
  } catch {
    return mockCandles(symbol, interval);
  }
}

export async function fetchNews(category: string = 'ALL', tag: string = ''): Promise<NewsArticle[]> {
  try {
    const res = await fetch(`${API_BASE}/news?category=${category}&tag=${tag}`);
    if (!res.ok) throw new Error('API offline');
    const json = await res.json();
    return json.data;
  } catch {
    let filtered = [...SAMPLE_NEWS];
    if (category !== 'ALL') {
      filtered = filtered.filter(n => n.category === category);
    }
    if (tag) {
      filtered = filtered.filter(n => n.tags.includes(tag));
    }
    return filtered;
  }
}

export async function fetchFiiDiiFlows(): Promise<FiiDiiFlow[]> {
  try {
    const res = await fetch(`${API_BASE}/flows/fii-dii`);
    if (!res.ok) throw new Error('API offline');
    const json = await res.json();
    return json.data;
  } catch {
    return SAMPLE_FII_DII;
  }
}

export async function fetchCalendarEvents(): Promise<CalendarEvent[]> {
  try {
    const res = await fetch(`${API_BASE}/calendar/events`);
    if (!res.ok) throw new Error('API offline');
    const json = await res.json();
    return json.data;
  } catch {
    return SAMPLE_CALENDAR;
  }
}

export async function askAiAssistant(query: string, contextSymbol: string = 'NIFTY50'): Promise<{ answer: string; grounding?: string[] }> {
  try {
    const res = await fetch(`${API_BASE}/ai/assistant`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ query, contextSymbol })
    });
    if (!res.ok) throw new Error('AI Assistant API offline');
    const json = await res.json();
    return json.data;
  } catch {
    return {
      answer: `**PulseMarket AI Analysis for ${contextSymbol}**\n\nBased on recent 5-minute technical indicator data:\n- **RSI (14)** is sitting at **61.4**, indicating solid momentum above neutral 50.\n- **Supertrend (10,3)** remains in **UP** posture anchored at ₹24,702.50.\n- **Option Chain PCR** stands at **1.14** with Max Pain positioned at ₹24,800.\n\n*Note: This analysis is automatically generated by mathematical indicator aggregation and is NOT investment advice.*`
    };
  }
}
